### ISSUE TITLE
Google Apps Profiles API is deprecated

### ISSUE THREAD

**Issue by aryelnr** [GPCsolutions/google-shared-contacts-client#2]
Hi, could you help me here?
I run this command
```python shared_contacts_profiles.py --admin=xpto@domain.com.br --export=ml.csv```

But I Receive this error
```
### Exporting contacts/profiles to CSV file: ml.csv
Retrieving contacts... (0 retrieved so far)
All contacts retrieved: 0 total
Retrieving profiles... (0 retrieved so far)
Traceback (most recent call last):
  File "shared_contacts_profiles.py", line 1180, in <module>
    main()
  File "shared_contacts_profiles.py", line 1175, in main
    contacts_manager.ExportMsOutlookCsv(contact_entries, profile_entries, export_csv_file)
  File "shared_contacts_profiles.py", line 552, in ExportMsOutlookCsv
    profile_entries))
  File "shared_contacts_profiles.py", line 742, in writerows
    for row in rows:
  File "shared_contacts_profiles.py", line 260, in GetAllProfiles
    desired_class=gdata.contacts.data.ProfilesFeed)
  File "C:\Python27\lib\site-packages\gdata\client.py", line 640, in get_feed
    **kwargs)
  File "C:\Python27\lib\site-packages\gdata\client.py", line 319, in request
    RequestError)
gdata.client.RequestError: Server responded with: 403, The Google Apps Profiles API has been officially deprecated. See https://developers.google.com/google-apps/profiles/ for more information.
```

**Comment by rdoursenaud** [comment]
The error is quite clear. The API used to retrieve the profiles is deprecated.
The code needs to be ported to use the new [Directory API](https://developers.google.com/admin-sdk/directory/) from the Google Apps Admin SDK.
I'll give it a try.

**Comment by rdoursenaud** [comment]
After having a quick glance at the code, I believe this will need a major redesign of the application.
I don't quite have the incentive to tackle this at the moment.
Any help appreciated.

**Comment by rdoursenaud** [comment]
For the record, the work that needs to be done is:
- [ ] Query Users from the Directory API instead of the Profiles API (https://developers.google.com/admin-sdk/directory/v1/reference/users/list)
- [ ] Handle a different results pagination method
- [ ] Handle and parse the JSON response instead of the gdata structure
- [ ] Add an Outlook serializer for the JSON data

In the meantime, if excluding the shared profiles informations from your export is an acceptable tradeoff, I think you can comment line 1174 to only export the contacts.
